---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msb
  name: msb
spec:
  selector:
    matchLabels:
      app: msb
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: msb
    spec:
      containers:
      - image: quay.io/bkthong/serviceb:odo
        imagePullPolicy: IfNotPresent
        name: msb
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: msb
  name: msb
spec:
  ports:
  - name: http-node
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: msb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msb
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: msb
            port:
              number: 8080
